// react/src/AppLayout.jsx
import styled from "styled-components";

const LayoutContainer = styled.div`
  height: 100vh;
  width: 100%;
  display: flex;
  flex-direction: column;
`;

const Aside = styled.aside`
  margin-bottom: 10px;
`;

const Main = styled.main`
  flex: 1;
  height: 100%;
`;

const Header = styled.header`
  @media (max-width: 767px) {
    order: 2;
  }
`;

function AppLayout({ headline, newsletter, children }) {
  console.log("render <AppLayout />");
  return (
    <LayoutContainer>
      <Aside>{newsletter}</Aside>
      <Header>{headline}</Header>
      <Main>{children}</Main>
    </LayoutContainer>
  );
}

export default AppLayout;

// vue/src/components/AppLayout.vue
<template>
  <div id="app-layout">
    <aside>
      <slot name="newsletter"></slot>
    </aside>
    <header>
      <slot name="headline"></slot>
    </header>
    <main>
      <slot></slot>
    </main>
  </div>
</template>
<script setup lang="ts">
import { onUpdated } from "vue";

console.log("render <AppLayout />");

onUpdated(() => {
  console.log("updated <AppLayout />");
});
</script>
<style lang="scss">
#app-layout {
  height: 100vh;
  display: flex;
  flex-direction: column;
}

main {
  flex: 1;
  height: 100%;
}

@media (max-width: 767px) {
  header {
    order: 2;
  }
}
</style>
