// react/src/ClearButton.jsx
import styled from "styled-components";

const Button = styled.a`
  padding: 4px 0;
  cursor: pointer;
  &:hover {
    text-decoration: underline;
  }
`;

const ClearButton = ({ onClick }) => {
  console.log("render <ClearButton />");
  return <Button onClick={onClick}>Clear completed</Button>;
};

export default ClearButton;

// vue/src/components/ClearButton.vue
<template>
  <a @click="onClick()">clear completed</a>
</template>

<script setup lang="ts">
import { onUpdated } from "vue";

console.log("render <ClearButton />");

onUpdated(() => {
  console.log("updated <ClearButton />");
});

defineProps({
  onClick: {
    type: Function,
    default: () => {
      // no op
    },
  },
});
</script>

<style scoped lang="scss">
a {
  padding: 4px 0;
  cursor: pointer;

  &:hover {
    text-decoration: underline;
  }
}
</style>
