// react/src/FilterButton.jsx
import PropTypes from "prop-types";
import { useContext } from "react";
import styled from "styled-components";
import AppContext from "./AppContext";

const Button = styled.button`
  border-style: solid;
  border-width: 1px;
  border-color: ${(props) =>
    props.active ? (props) => props.theme.color : "transparent"};
  background-color: ${(props) => props.theme.bgColor};
  color: ${(props) => props.theme.color};
  padding: 4px;
  border-radius: 3px;
  background: none;
`;

const FilterButton = ({ label, onClick, active }) => {
  console.log("render <FilterButton />");
  const { theme } = useContext(AppContext);

  return (
    <Button theme={theme} onClick={onClick} active={active}>
      {label}
    </Button>
  );
};

FilterButton.propTypes = {
  label: PropTypes.string.isRequired,
  active: PropTypes.bool,
  onCLick: PropTypes.func,
};

FilterButton.defaultProps = {
  active: false,
  onClick: () => {},
};

export default FilterButton;

// vue/src/components/FilterButton.vue
<template>
  <button
    :style="{
      borderColor: active ? theme.color : 'transparent',
      backgroundColor,
      color,
    }"
    @click="onClick()"
  >
    {{ label }}
  </button>
</template>

<script setup lang="ts">
console.log("render <FilterButton />");

onUpdated(() => {
  console.log("updated <FilterButton />");
});

import { useTodosStore } from "@/stores/todos";
import { storeToRefs } from "pinia";
import { onUpdated } from "vue";

// interface ButtonProps {
//   label: string;
//   active: boolean;
//   onClick: () => void;
// }

//defineProps<ButtonProps>();

// defineProps({
//   label: String,
//   active: Boolean,
//   onClick: Function,
// });

defineProps({
  label: {
    type: String,
    required: true,
  },
  active: {
    type: Boolean,
    default: false,
  },
  onClick: { type: Function, required: true },
});

const { theme } = storeToRefs(useTodosStore());
const { backgroundColor, color } = theme.value;
</script>
<style scoped lang="scss">
button {
  border-style: solid;
  border-width: 1px;
  padding: 7px;
  border-radius: 3px;
  background: none;
  cursor: pointer;
  display: block;
}
</style>
