// react/src/Headline.jsx
import { string } from "prop-types";
import styled from "styled-components";

const Headline = styled.h1`
  color: ${(props) => props.color};
  font-size: 100px;
  font-weight: 100;
  text-align: center;
`;

const HeadlineComponent = ({ color }) => {
  return <Headline color={color}>todos</Headline>;
};

HeadlineComponent.propTypes = {
  color: string,
};

HeadlineComponent.defaultProps = {
  color: "rgba(175, 47, 47, 0.15)",
};

export default HeadlineComponent;

// vue/src/components/Headline.vue
<template>
  <h1 :style="{ color }">{{ text }}</h1>
</template>
<script lang="ts" setup>
import { type PropType, computed } from "vue";

export type HeadlineColor = "green" | "red" | "gray";

const prop = defineProps({
  fontColor: {
    type: String as PropType<HeadlineColor>,
    default: "red",
  },
  text: {
    type: String,
    required: true,
  },
});

const color = computed(() => {
  switch (prop.fontColor) {
    case "green":
      return "#0dbe9b";
    case "gray":
      return `rgb(109, 117, 130)`;
    default:
      return `rgba(175, 47, 47`;
  }
});
</script>
<style scoped lang="scss">
h1 {
  font-size: 100px;
  font-weight: 100;
  text-align: center;
}
</style>
