// react/src/MailForm.jsx
import { useState } from "react";
import styled from "styled-components";

const FormContainer = styled.form`
  color: white;
  background: #6e7582;
  display: flex;
  padding: 5px;
`;

const FormGroup = styled.fieldset`
  border: 0;
  padding: 0;
  flex: ${(props) => props.last && "1"};
  text-align: ${(props) => props.last && "right"};

  label {
    margin-left: ${(props) => (props.first ? "0px" : "10px")};
  }
`;

const FormLabel = styled.label`
  margin-right: 5px;
`;

function MailForm({ onSubscribeNewsletter }) {
  console.log("render <MailForm />");

  const handleSubmit = (evt) => {
    evt.preventDefault();
    onSubscribeNewsletter(firstName);
  };

  const [firstName, setFirstName] = useState("");
  const [email, setEmail] = useState("");
  const [frequency, setFrequency] = useState("monthly");

  return (
    <>
      <FormContainer onSubmit={handleSubmit}>
        <FormGroup first={true}>
          <FormLabel>first name</FormLabel>
          <input onChange={(evt) => setFirstName(evt.target.value)} />
        </FormGroup>
        <FormGroup>
          <FormLabel>email</FormLabel>
          <input onChange={(evt) => setEmail(evt.target.value)} />
        </FormGroup>
        <FormGroup>
          <FormLabel>frequency</FormLabel>
          <select onChange={(evt) => setFrequency(evt.target.value)}>
            <option>weekly</option>
            <option>monthly</option>
          </select>
        </FormGroup>
        <FormGroup last={true}>
          <button type="submit">subscribe to newsletter</button>
        </FormGroup>
      </FormContainer>
    </>
  );
}

export default MailForm;

// vue/src/components/MailForm.vue
<template>
  <form @submit.prevent="handleSubmit">
    <fieldset>
      <label>first name</label
      ><input :value="user.firstName" @input="handleFirstNameChange" />
    </fieldset>
    <fieldset><label>email</label><input v-model="user.mail" /></fieldset>
    <fieldset>
      <label>frequency</label
      ><select v-model="user.frequency">
        <option>weekly</option>
        <option>monthly</option>
      </select>
    </fieldset>
    <fieldset>
      <button type="submit">subscribe to newsletter</button>
    </fieldset>
  </form>
</template>

<script setup lang="ts">
import { onUpdated, reactive } from "vue";

console.log("render <MailForm />");

onUpdated(() => {
  console.log("updated <MailForm />");
});

type User = {
  firstName: string;
  mail: string;
  frequency: "weekly" | "monthly";
};

const user = reactive<User>({ firstName: "", mail: "", frequency: "weekly" });

const handleFirstNameChange = (evt: Event) => {
  user.firstName = (evt.target as HTMLInputElement).value;
  console.log(user.firstName);
};

const emit = defineEmits(["subscribe-newsletter"]);

const handleSubmit = () => {
  emit("subscribe-newsletter", user.firstName);
};
</script>

<style scoped lang="scss">
$gap: 5px;

form {
  color: white;
  background: #6e7582;
  display: flex;
  padding: $gap;
}

fieldset {
  border: 0;
  padding: 0;

  + fieldset {
    margin-left: $gap;
  }

  &:last-child {
    flex: 1;
    text-align: right;
  }
}

label {
  margin-right: $gap;
}
</style>
