// react/src/TodoItem.jsx
import { useContext, useState } from "react";
import styled from "styled-components";
import AppContext from "./AppContext";
import DeleteButton from "./DeleteButton";

const Container = styled.div`
  height: 30px;
  background: white;
  padding: 16px;
  display: flex;
  align-items: center;
  border: 0 solid #e6e6e6;
  border-bottom-width: 1px;
  > button {
    background: none;
  }
`;

const Item = styled.div`
  flex: 1;
  font-size: 24px;
  margin: 0 24px;
  text-decoration: ${(props) => (props.checked ? "line-through" : "normal")};
  > div {
    display: block;
    font-size: 70%;
  }
`;

const CheckButton = styled.button`
  width: 30px;
  height: 30px;
  border-radius: 15px;
  border: 1px solid #a0a0a0;
  display: flex;
  align-items: center;
  justify-content: center;
`;

const Check = styled.span`
  font-size: 20px;
  color: #9bd9cd;
  display: ${(props) => (props.visible ? "block" : "none")};
`;

const TodoItem = ({ todo }) => {
  const { todos, setTodos } = useContext(AppContext);
  const [hover, setHover] = useState(false);
  const [checkHover, setCheckHover] = useState(false);
  return (
    <Container
      onMouseEnter={() => setHover(true)}
      onMouseLeave={() => setHover(false)}
    >
      <CheckButton
        onMouseEnter={() => setCheckHover(true)}
        onMouseLeave={() => setCheckHover(false)}
        onClick={() => {
          const index = todos.findIndex((item) => item.id === todo.id);
          const updatedTodos = [...todos];
          updatedTodos[index] = {
            ...todo,
            checked: !todo.checked,
          };
          setTodos(updatedTodos);
        }}
      >
        <Check visible={todo.checked || checkHover}>✔️</Check>
      </CheckButton>
      <Item checked={todo.checked || false}>
        {todo.label}
        <div>{todo.date}</div>
      </Item>
      {hover && (
        <DeleteButton
          onClick={() => {
            setTodos([...todos.filter((item) => item.id != todo.id)]);
          }}
        />
      )}
    </Container>
  );
};

export default TodoItem;

// vue/src/components/TodoItem.vue
<template>
  <div>
    <div class="todo-item" @mouseover="onMouseOver" @mouseout="onMouseOut">
      <button class="check-button" @click="handleCheckClick()">
        <span v-show="todo.checked" class="check">✔️</span>
      </button>
      <div class="item-label" :class="{ 'is-crossed-out': isCrossedOut }">
        {{ todo.label }}
        <div>{{ todo.date }}</div>
      </div>
      <DeleteButton v-show="hover" :on-click="handleDeleteClick" />
    </div>
  </div>
</template>

<script setup lang="ts">
import DeleteButton from "./DeleteButton.vue";
import { useTodosStore } from "@/stores/todos";
import { computed, ref } from "vue";

const hover = ref(false);

const onMouseOver = () => {
  return (hover.value = true);
};
const onMouseOut = () => {
  return (hover.value = false);
};

interface Props {
  todo: {
    id: number;
    label: string;
    date: string;
    checked: boolean;
  };
}

const { toggleCheckTodo, removeTodo } = useTodosStore();

const props = defineProps<Props>();
const isCrossedOut = computed(() => props.todo.checked === true);

const handleDeleteClick = () => {
  removeTodo(props.todo);
};

const handleCheckClick = () => {
  toggleCheckTodo(props.todo);
};
</script>

<style scoped lang="scss">
.todo-item {
  background: white;
  padding: 16px;
  display: flex;
  align-items: center;
  border: 0 solid #e6e6e6;
  border-bottom-width: 1px;
}

.check-button {
  width: 30px;
  height: 30px;
  border-radius: 15px;
  border: 1px solid #a0a0a0;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}

.check {
  color: transparent;
  text-shadow: 0 0 0 #0dbe9b;
}

.item-label {
  flex: 1;
  font-size: 24px;
  margin: 0 24px;

  > div {
    display: block;
    font-size: 70%;
  }

  &.is-crossed-out {
    text-decoration: line-through;
  }
}
</style>
