// vue/src/components/DeleteButton.vue
<template>
  <button @click="onClick()">{{ label }}</button>
</template>

<script setup lang="ts">
import { onUpdated } from "vue";

console.log("render <DeleteButton />");

onUpdated(() => {
  console.log("updated <DeleteButton />");
});

defineProps({
  label: {
    type: String,
    default: "❌",
  },
  onClick: {
    type: Function,
    default: () => {
      // no op
    },
  },
});
</script>

<style scoped lang="scss">
button {
  border: none;
  font-size: 30px;
  cursor: pointer;
  background: none;
}
</style>

// react/src/DeleteButton.jsx
import PropTypes from "prop-types";
import styled from "styled-components";

const Button = styled.button`
  border: none;
  font-size: 30px;
`;

const DeleteButton = ({ onClick, label }) => {
  console.log("render <DeleteButton />");
  return <Button onClick={onClick}>{label}</Button>;
};

DeleteButton.propTypes = {
  label: PropTypes.string,
  onClick: PropTypes.func,
};

DeleteButton.defaultProps = {
  label: "❌",
  onClick: () => {},
};

export default DeleteButton;
