// vue/src/components/FilterButtons.vue
<template>
  <div class="filter-buttons">
    <FilterButton
      label="All"
      :active="filterIndex === FilterIndex.ALL"
      :on-click="handleAllClick"
    />
    <FilterButton
      label="Active"
      :active="filterIndex === FilterIndex.UNCHECKED"
      :on-click="handleActiveClick"
    />
    <FilterButton
      label="Completed"
      :active="filterIndex === FilterIndex.CHECKED"
      :on-click="handleCompletedClick"
    />
  </div>
</template>

<script setup lang="ts">
console.log("render <FilterButtons />");

onUpdated(() => {
  console.log("updated <FilterButtons />");
});

import FilterButton from "./FilterButton.vue";
import { useTodosStore } from "@/stores/todos";
import { FilterIndex } from "@/stores/todos";
import { storeToRefs } from "pinia";
import { onUpdated } from "vue";

const store = useTodosStore();
const { filterIndex } = storeToRefs(useTodosStore());

const handleAllClick = () => {
  store.setFilterIndex(FilterIndex.ALL);
};

const handleActiveClick = () => {
  store.setFilterIndex(FilterIndex.UNCHECKED);
};

const handleCompletedClick = () => {
  store.setFilterIndex(FilterIndex.CHECKED);
};
</script>

<style scoped lang="scss">
.filter-buttons {
  display: flex;

  > * + * {
    margin-left: 16px;
  }
}
</style>

// react/src/FilterButtons.jsx
import { useState, useContext } from "react";
import styled from "styled-components";
import AppContext from "./AppContext";
import FilterButton from "./FilterButton";

const Container = styled.div`
  display: flex;
  > * + * {
    margin-left: 16px;
  }
`;

const FilterButtons = () => {
  console.log("render <FilterButtons />");
  const { setFilterIndex } = useContext(AppContext);
  const [index, setIndex] = useState(0);
  return (
    <Container>
      <FilterButton
        onClick={() => {
          setIndex(0);
          setFilterIndex(0);
        }}
        active={index === 0}
        label="All"
      />
      <FilterButton
        onClick={() => {
          setIndex(1);
          setFilterIndex(1);
        }}
        active={index === 1}
        label="Active"
      />
      <FilterButton
        onClick={() => {
          setIndex(2);
          setFilterIndex(2);
        }}
        active={index === 2}
        label="Completed"
      />
    </Container>
  );
};

export default FilterButtons;
