// vue/src/components/Status.vue
<template>
  <LeftItems :label="label" :todos-left="todosLeft" />
</template>

<script setup lang="ts">
console.log("render <Status />");

onUpdated(() => {
  console.log("updated <Status />");
});

import { useTodosStore } from "@/stores/todos";
import { storeToRefs } from "pinia";
import { computed, onUpdated } from "vue";
import LeftItems from "./LeftItems.vue";

const { todosLeft } = storeToRefs(useTodosStore());
// this is an example where view (label) does not update without computed
const label = computed(() =>
  todosLeft.value > 1 ? "items left" : "item left"
);
</script>

// react/src/Status.jsx
import { useContext } from "react";
import AppContext from "./AppContext";

const Status = () => {
  console.log("render <Status />");
  const { todos } = useContext(AppContext);
  const todosLeft = todos.reduce((count, todo) => {
    if (!todo.checked) return count + 1;
    return count;
  }, 0);
  const label = todosLeft > 1 ? "items left" : "item left";
  return (
    <div>
      {todosLeft} {label}
    </div>
  );
};

export default Status;
