// vue/src/components/TodoList.vue
<template>
  <div class="todo-list">
    <TodoItem v-for="todo in filteredTodos" :key="todo.id" :todo="todo" />
  </div>
</template>

<script setup lang="ts">
console.log("render <TodoList />");

onUpdated(() => {
  console.log("updated <TodoList />");
});

import { useTodosStore } from "@/stores/todos";
import { storeToRefs } from "pinia";
import TodoItem from "./TodoItem.vue";
import { onUpdated } from "vue";

const { filteredTodos } = storeToRefs(useTodosStore());
</script>

// react/src/TodoList.jsx
import styled from "styled-components";
import { useContext, useState, useEffect } from "react";
import TodoItem from "./TodoItem";
import AppContext from "./AppContext";

const Container = styled.div``;

const TodoList = () => {
  console.log("render <TodoList />");

  const { todos, filterIndex } = useContext(AppContext);
  const [filteredTodos, setFilteredTodos] = useState([]);
  useEffect(() => {
    if (filterIndex === 0) {
      setFilteredTodos([...todos]);
    } else if (filterIndex === 1) {
      setFilteredTodos([...todos.filter((todo) => !todo.checked)]);
    } else {
      setFilteredTodos([...todos.filter((todo) => todo.checked)]);
    }
  }, [filterIndex, todos]);
  return (
    <Container>
      {filteredTodos.map((todo) => (
        <TodoItem key={todo.id} todo={todo} />
      ))}
    </Container>
  );
};

export default TodoList;
