// react/src/Todos.jsx
import { useState } from "react";
import styled from "styled-components";
import ActionBar from "./ActionBar";
import TodoInput from "./TodoInput";
import TodoList from "./TodoList";
import AppContext from "./AppContext";
import theme from "./theme";
import translation from "./translation";

const Container = styled.div`
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 25px 50px 0 rgba(0, 0, 0, 0.1);
`;

const Todos = () => {
  const [todos, setTodos] = useState([]);
  const [filterIndex, setFilterIndex] = useState(0);
  return (
    <AppContext.Provider
      value={{
        todos,
        setTodos,
        filterIndex,
        setFilterIndex,
        theme: theme.LIGHT,
        translation,
      }}
    >
      <Container>
        <TodoInput />
        <TodoList />
        {todos.length > 0 && <ActionBar />}
      </Container>
    </AppContext.Provider>
  );
};

export default Todos;

// vue/src/views/Todos.vue
<template>
  <div class="todos">
    <TodoInput />
    <TodoList />
    <ActionBar v-if="showActionBar" />
  </div>
</template>

<script setup lang="ts">
import { useTodosStore } from "@/stores/todos";
import { computed } from "vue";
import ActionBar from "@/components/ActionBar.vue";
import TodoInput from "@/components/TodoInput.vue";
import TodoList from "@/components/TodoList.vue";

const { todos } = useTodosStore();
const showActionBar = computed(() => todos.length > 0);
</script>

<style scoped lang="scss">
.todos {
  box-shadow: 0 2px 4px 0 rgba(0, 0, 0, 0.2), 0 25px 50px 0 rgba(0, 0, 0, 0.1);
}
</style>
